### ISSUE TITLE
BluetoothAddressType property missing from BluetoothLEAdvertisementReceivedEventArgs

### ISSUE THREAD

**Issue by shyun3** [dlech/bleak-winrt#2]
The [BluetoothLEAdvertisementReceivedEventArgs.BluetoothAddressType](https://docs.microsoft.com/en-us/uwp/api/windows.devices.bluetooth.advertisement.bluetoothleadvertisementreceivedeventargs.bluetoothaddresstype?view=winrt-22000#Windows_Devices_Bluetooth_Advertisement_BluetoothLEAdvertisementReceivedEventArgs_BluetoothAddressType) does not seem to be accessible from the Python `BluetoothLEAdvertisementReceivedEventArgs` type.

**Comment by dlech** [comment]
This property was introduced in Window 10 build 19041 but this package is currently built using the SDK for build 18362.

https://github.com/dlech/bleak-winrt/blob/5adb9d096a63c126de7532fd188e1315b397dfb0/generate.ps1#L3
